version: '{build}'
image: 'Visual Studio 2017'
clone_depth: 1
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile
build_script:
  - yarn build
test_script:
  - yarn test -c=ci
  - ps: |
      if ($env:CODECOV_TOKEN)
      {
        yarn global add codecov
        codecov --disable=gcov -f dist/coverage/ng-log/lcov.info -F unit
      }
cache:
  - node_modules -> yarn.lock
  - "%LOCALAPPDATA%\\Yarn"
