sudo: false
dist: trusty
language: node_js
git:
  depth: 1
matrix:
  include:
    - os: linux
      node_js: "node"
    - os: osx
      node_js: "node"
  fast_finish: true
install:
  - yarn install --frozen-lockfile
script:
  - yarn build
  - yarn test -c=ci
cache: yarn
