resources:
  repositories:
    - repository: templates
      type: github
      name: DagonMetric/ng-workspace-configs
      endpoint: github-dagonmetric-connection

stages:
  - template: azure-pipelines/multi-platform-build-stage.yml@templates
