resources:
  repositories:
    - repository: templates
      type: github
      name: DagonMetric/ci-template
      endpoint: github-dagonmetric-connection

stages:
  - template: azure-pipelines/nodejs/multi-platform-build-stage.yml@templates
